server:
  port: 0

spring:
  application:
    name: micro-service
  data:
    redis:
      port: 6379
      host: localhost
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, busenv, refresh, beans, httptrace
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]\n"

# https://velog.io/@wwlee94/Spring-ELK%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%98%EC%97%AC-Kafka-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%A1%9C%EA%B7%B8-%EC%88%98%EC%A7%91